import assert from 'node:assert/strict';
import test from 'node:test';
import {updateOperationHistory} from '../../src/ui/operationHistory.ts';
import type {OperationHistoryEntry} from '../../src/ui/operationHistory.ts';
import type {OperationRecord} from '../../src/types/git.ts';
/** 操作记录仅使用独立测试身份，不触发 Git。 */
function record(id:string,sequence:number,ended=false,repositoryId='r'):OperationRecord{return {progress:{handle:{operationId:id,repositoryId},sequence,kind:'fetch',phase:ended?'completed':'transferring',counts:null,startedAt:1},result:ended?{outcome:'succeeded',operationId:id,kind:'fetch',commitOid:null,branchName:null,clonePath:null,refresh:{status:'notApplicable'}}:null};}
test('跨仓库及倒序事件不覆盖原任务，重复序号不重复追加事件',()=>{let history=updateOperationHistory([],record('a',3),'原项目',1);history=updateOperationHistory(history,record('a',3),'新显示名',2);history=updateOperationHistory(history,record('a',2),'旧事件',3);history=updateOperationHistory(history,record('a',4,false,'foreign'),'其他项目',4);assert.equal(history.length,1);assert.equal(history[0]?.target,'原项目');assert.equal(history[0]?.repositoryId,'r');assert.equal(history[0]?.sequence,3);assert.equal(history[0]?.events.length,1);});
test('终态最多200条但保留活跃任务，终态不会被迟到进度撤销',()=>{let history:OperationHistoryEntry[]=[];history=updateOperationHistory(history,record('active',0),'项目',0);for(let i=0;i<205;i++)history=updateOperationHistory(history,record(`done${i}`,1,true),'项目',i+1);assert.equal(history.length,201);assert.ok(history.some(x=>x.id==='active'));assert.ok(!history.some(x=>x.id==='done0'));assert.ok(history.some(x=>x.id==='done204'));history=updateOperationHistory(history,record('done204',2),'项目',999);assert.equal(history.find(x=>x.id==='done204')?.outcome,'succeeded');});
test('单任务仅保留最近100条事件且结束时间稳定',()=>{let history:OperationHistoryEntry[]=[];for(let i=0;i<120;i++)history=updateOperationHistory(history,record('a',i),'项目',i);assert.equal(history[0]?.events.length,100);assert.equal(history[0]?.events[0]?.sequence,20);history=updateOperationHistory(history,record('a',120,true),'项目',120);history=updateOperationHistory(history,record('a',120,true),'项目',130);assert.equal(history[0]?.finishedAt,120);assert.equal(history[0]?.events.length,100);});
test('失败原因、本地刷新失败及克隆残留路径独立保留',()=>{const value=record('a',2);value.result={outcome:'unknown',operationId:'a',kind:'fetch',error:{code:'WRITE_OUTCOME_UNKNOWN',retryable:false},cloneRecovery:{path:'/fixture/recovery',stage:'download'},refresh:{status:'failed',error:{code:'ACCESS_DENIED',retryable:false}}};const entry=updateOperationHistory([],value,'项目',2)[0];assert.equal(entry?.error?.code,'WRITE_OUTCOME_UNKNOWN');assert.equal(entry?.refreshError?.code,'ACCESS_DENIED');assert.equal(entry?.recoveryPath,'/fixture/recovery');assert.equal(entry?.outcome,'unknown');assert.equal(Object.hasOwn(entry??{},'result'),false);});
