import assert from 'node:assert/strict';
import test from 'node:test';
import {createDiffPages} from '../../src/hooks/diffPagesController.ts';
import type {DiffPage} from '../../src/types/diff.ts';
/** 短页模拟后台文本预算。 */
function page(start:number,count:number,offset=0):DiffPage{return {startRow:start,rows:Array.from({length:count},(_,i)=>({kind:'add',oldLine:null,newLine:start+i+1,text:`行${start+i}`,byteOffset:offset,nextByteOffset:offset?null:16384})),nextRow:start+count};}
test('短页补齐与跳读、行缓存淘汰',async()=>{const calls:number[]=[];const cache=createDiffPages(20000,async(start,count,offset)=>{calls.push(start);return page(start,Math.min(count,3),offset)});cache.activate();await cache.ensure(19980,19995);assert.equal(cache.row(19994)?.newLine,19995);assert.deepEqual(calls,[19980,19983,19986,19989,19992]);for(let i=0;i<50;i++)await cache.ensure(i*100,i*100+3);assert.ok(cache.getSnapshot().rows.size<=128);assert.equal(cache.row(19994),undefined);});
test('关闭丢弃迟到页、错误停止自动读取',async()=>{let finish:(p:DiffPage)=>void=()=>{};let calls=0;const cache=createDiffPages(100,async()=>{calls++;if(calls===1)return new Promise(r=>finish=r);throw {code:'STALE_REQUEST'}});cache.activate();const task=cache.ensure(0,1);await Promise.resolve();cache.dispose();finish(page(0,1));await task;assert.equal(cache.row(0),undefined);cache.activate();await cache.ensure(0,1);await cache.ensure(2,3);assert.equal(calls,2);assert.equal(cache.getSnapshot().error?.code,'STALE_REQUEST');});
test('长行替换单段，保留相邻缓存行',async()=>{const cache=createDiffPages(100,async(start,count,offset)=>page(start,count,offset));cache.activate();await cache.ensure(0,10);await cache.segment(4,16384);assert.equal(cache.row(4)?.byteOffset,16384);assert.equal(cache.row(5)?.byteOffset,0);await cache.segment(4,0);assert.equal(cache.row(4)?.byteOffset,0);});
test('折叠后的非连续可见区不读取隐藏正文，也不会因页数多而反复淘汰',async()=>{const calls:number[]=[];const cache=createDiffPages(10000,async(start,count)=>{calls.push(start);return page(start,count)});cache.activate();const indices=Array.from({length:80},(_,i)=>i*100);await cache.ensureRows(indices);assert.equal(calls.length,80);assert.deepEqual(calls,indices);assert.ok(indices.every(i=>cache.row(i)));});
